title: TinyTalk
baseurl: ""
url: "https://tuannv-j2c.github.io"

markdown: kramdown
highlighter: rouge

# Tell Jekyll to process .md files in blog subdirectories
# (by default it skips directories that don't start with _)
include:
  - tinytalk.me
  - notes

exclude:
  - README.md
